name: Github to docker
on:
  push:
    banches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: push to dockerhub
        if: github.ref == 'refs/heads/master'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: israelrg/github_actions_prueba:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}